[package]
name = "kafka-example"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = "0.37.0"
tokio = { version = "1.43.0", features = ["full"] }
uuid = { version = "1.15.1", features = ["v4"] }
