[package]
name = "kafka-example"
version = "0.1.0"
edition = "2024"


[workspace]
resolver = "2"

[dependencies]
rdkafka = "0.37.0"
schema_registry_converter = { version = "4.4.0", features = ["easy", "avro"] }
tokio = { version = "1.45.1", features = ["full"] }
